CREATE SEQUENCE SEQ_ACIDENTES
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE TABLE TBL_ACIDENTES (
    ACIDENTE_ID INTEGER DEFAULT SEQ_ACIDENTES.NEXTVAL NOT NULL,
    ENDERECO VARCHAR(100) NOT NULL,
    DATA_OCORRENCIA DATE NOT NULL,
    VITIMA VARCHAR(100) NOT NULL,
    CAUSADOR VARCHAR(100) NOT NULL
);